# Generated by Django 3.0.6 on 2020-05-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('websiteURL', models.URLField()),
                ('crunchbaseURL', models.URLField()),
                ('videoURL', models.URLField()),
                ('tags', models.CharField(max_length=200)),
                ('companyID', models.CharField(max_length=200)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
