# Generated by Django 3.0.6 on 2020-05-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
